const db=require('./conn').db
const mongoose=require('./conn').mongoose

const projectSchema=mongoose.Schema({     
    name:{
        type:String
    },
    img1:{
        type:String
    },
    tit1:{
        type:String
    },
    img2:{
        type:String
    },
    tit2:{
        type:String
    },
    img3:{
        type:String
    },
    tit3:{
        type:String
    },
    para:{
        type:String
    },
    head2:{
        type:String
    },
    topicimg1:{
        type:String
    },
    topic1:{
        type:String
    },
    topicimg2:{
        type:String
    },
    topic2:{
        type:String
    },
    topicimg3:{
        type:String
    },
    topic3:{
        type:String
    },
    topicimg4:{
        type:String
    },
    topic4:{
        type:String
    },
    topicimg5:{
        type:String
    },
    topic5:{
        type:String
    },
    topicimg6:{
        type:String
    },
    topic6:{
        type:String
    },
    resortimg1:{
        type:String
    },
    resort1:{
        type:String
    },
    resortimg2:{
        type:String
    },
    resort2:{
        type:String
    },
    resortimg3:{
        type:String
    },
    resort3:{
        type:String
    },
    resortimg4:{
        type:String
    },
    resort4:{
        type:String
    },
    resortimg5:{
        type:String
    },
    resort5:{
        type:String
    },
    resortimg6:{
        type:String
    },
    resort6:{
        type:String
    },
    tourimg1:{
        type:String
    },
    tour1:{
        type:String
    },
    tourimg2:{
        type:String
    },
    tour2:{
        type:String
    },
    tourimg3:{
        type:String
    },
    tour3:{
        type:String
    },
    tourimg4:{
        type:String
    },
    tour4:{
        type:String
    },
    tourimg5:{
        type:String
    },
    tour5:{
        type:String
    },
    tourimg6:{
        type:String
    },
    tour6:{
        type:String
    }
})

let projectModel=mongoose.model('projects',projectSchema)
module.exports={projectModel}